services:

# Server
  go-server:
    container_name: go-server
    # имя создаваемого образа
    image: naeel/iman:latest
    build:
    # путь до докерфайла
      context: ./
    # докерфайл
      dockerfile: ServerDockerFile
    
    ports:
    # published port - внешний, доступ по CURL или HTTP
      - published: 8100
    # порт контейнера. задан в коде server port http.ListenAndServe(":8080", router)
        target: 8080
        protocol: tcp
    networks:
      - localnet


volumes:
 oblbibl:

networks:
  localnet:
    driver: bridge

