services:

# Server
  go-server:
    container_name: go-server
    # имя создаваемого образа
    image: naeel/iman:latest
    build:
    # путь до докерфайла
      context: ./
    # докерфайл
      dockerfile: ServerDockerFile
    # переменные окружения для сервера
    environment:
      CONTAINER_PORT: "8080"
      HOST_PORT: "8100"
    ports:
    # server port http.ListenAndServe(":8080", router)
      - target: ${HOST_PORT}
#      - target: "8080"
    # published port - внешний, доступ по CURL или HTTP
        published: ${CONTAINER_PORT}
        protocol: tcp
    networks:
      - localnet


volumes:
 oblbibl:

networks:
  localnet:
    driver: bridge

