# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Docker Compose CI

on: # workflow_dispatch
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Update to your Go version

      - name: Go UNIT Test
        run:  go test -v ./internal/tests/unit

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build with Docker Compose
        run: docker compose build

      - name: docker compose WHOami
        run:  docker compose run --rm go-server echo -n "pwd "; pwd; echo -n "whoami  "; whoami
      - name: LS -R
        run:  docker compose run --rm go-server ls -R


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     

      - name: docker PUSH
        run:  docker-compose push

      - name: Start services and run integration tests
        run: |
          docker compose up -d
          docker compose exec -T go-server go test ./internal/tests/integration -v
          docker compose  down

