name: Go Docker Compose CI

on:
  push:
    branches: [ "based" ]

env:
  EXTERNAL_PORT: "8100"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER
          newgrp docker
          docker --version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build with Docker Compose
        run: docker compose build

      - name: Run unit tests
        run: go test -v ./internal/tests/unit

      - name: Start services and run tests
        run: |
          docker compose up -d
          sleep 10 # Wait for services to start
          
          # Run tests inside container
          docker compose exec -T -e PORTOS="8080" go-server go test -v ./internal/tests/unit
          
          # Run tests outside container
          env PORTOS="8100" go test -v ./internal/tests/unit
          
          docker compose down