# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Docker Compose CI

on: # workflow_dispatch
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Update to your Go version

      - name: Go Test
        run:  go test -v ./...

      # - name: Set up Docker
      #   uses: docker/setup-qemu-action@v1
      #   uses: docker/setup-buildx-action@v1
      #   uses: docker/setup-action@v1     


      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build with Docker Compose
        run: docker compose build

      - name: docker compose WHOami
        run:  docker compose run --rm go-server echo -n "pwd "; pwd; echo -n "whoami  "; whoami
#          docker compose run --rm go-server echo -n "whoami  "; whoami
      - name: LS -R
        run:  docker compose run --rm go-server ls -R


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     
      # - name: docker push
      #   run:  docker-compose push



      # - name: Run tests
      #   run: |
      #     ls -R
        #run: docker compose run --rm go-server go test -v -short ./...
        #run: docker-compose run go-server go test -v ./...

      - name: Start services and run integration tests
        run: |
          docker compose up -d
          docker compose exec -T go-server go env GOFLAGS
          docker compose exec -T go-server go test -v -tags=integration ./...
          docker compose  down

#docker compose exec go-server go test -tags=integration -v ./...